### ISSUE TITLE
add build script presets and stages

### ISSUE THREAD

**Issue by myzhang1029** [myzhang1029/zcbe#3]
v0.3 task:  
e.g. in conf.toml:
```toml
[build]
preset="cmake" # or
preset="autoconf" # or
preset="buildsh" # (optional)
# or
[build.stages]
configure=[
'./autogen.sh',
'./configure',
]
make=[
'make'
]
install=[
'make install'
]
clean=[
'make distclean'
]
```
and the `clean` stage can be run automatically if build failed and debug is not set.  
The old `build.sh` way will still work, and the `buildsh` preset says that explicitly.
The commands are run inside a shell (`asyncio.create_subprocess_shell`)
If any command failed, things won't continue.
